[package]
name = "ps-parser"
version = "0.1.0"
edition = "2024"
build = "build.rs"

#[lib]
#path = "src/lib.rs"

[dependencies]
log = "0.4.27"
pest = "2.7.8"
pest_derive = "2.7"
smart-default = "0.7.1"
unicode-normalization = "0.1"

[build-dependencies]
pest_generator = "2.7"
