[package]
name = "ps-parser"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
path = "src/lib.rs"

[dependencies]
pest = "2.7"
pest_derive = "2.7"

[build-dependencies]
pest_generator = "2.7"
